lab4/Models/AdditionalService.cs
using System;
using System.Collections.Generic;

namespace lab4;

public partial class AdditionalService
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Description { get; set; } = null!;

    public decimal Price { get; set; }

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}

lab4/Models/Client.cs
using System;
using System.Collections.Generic;

namespace lab4.Models;

public partial class Client
{
    public int Id { get; set; }

    public string Fio { get; set; } = null!;

    public DateTime DateOfBirth { get; set; }

    public string Sex { get; set; } = null!;

    public string Address { get; set; } = null!;

    public string Series { get; set; } = null!;

    public long Number { get; set; }

    public long Discount { get; set; }

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}

lab4/Models/Employee.cs
using System;
using System.Collections.Generic;

namespace lab4;

public partial class Employee
{
    public int Id { get; set; }

    public string Fio { get; set; } = null!;

    public string JobTitle { get; set; } = null!;

    public int Age { get; set; }

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}

lab4/Models/ErrorViewModel.cs
namespace lab4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab4/Models/Hotel.cs
using System;
using System.Collections.Generic;

namespace lab4;

public partial class Hotel
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Country { get; set; } = null!;

    public string City { get; set; } = null!;

    public string Address { get; set; } = null!;

    public string Phone { get; set; } = null!;

    public int Stars { get; set; }

    public string TheContactPerson { get; set; } = null!;

    public byte[] Photo { get; set; } = null!;

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}

lab4/Models/TypesOfRecreation.cs
using System;
using System.Collections.Generic;

namespace lab4.Models;

public partial class TypesOfRecreation
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Description { get; set; } = null!;

    public string Restrictions { get; set; } = null!;

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}

lab4/Models/Voucher.cs
using System;
using System.Collections.Generic;
using lab4.Models;

namespace lab4;

public partial class Voucher
{
    public int Id { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime ExpirationDate { get; set; }

    public int TypeOfRecreationId { get; set; }

    public int ClientId { get; set; }

    public bool Reservation { get; set; }

    public bool Payment { get; set; }

    public virtual Client Client { get; set; } = null!;

    public virtual TypesOfRecreation TypeOfRecreation { get; set; } = null!;
}

lab4/Controllers/ClientController.cs
using lab4.Data;
using Microsoft.AspNetCore.Mvc;

namespace lab4.Controllers
{
    public class ClientController : Controller
    {
        private TouristAgency1Context db;

        public ClientController(TouristAgency1Context context)
        {
            db = context;
        }

        [ResponseCache(CacheProfileName = "ModelCache")]
        public IActionResult ShowTable()
        {
            var clients = db.Clients.ToList();
            return View(clients);
        }
    }
}

lab4/Controllers/HomeController.cs
using lab4.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace lab4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab4/Controllers/TypesOfRecrationController.cs
using lab4.Data;
using Microsoft.AspNetCore.Mvc;

namespace lab4.Controllers
{
    public class TypesOfRecrationController : Controller
    {
        private TouristAgency1Context db;

        public TypesOfRecrationController(TouristAgency1Context context)
        {
            db = context;
        }

        [ResponseCache(CacheProfileName = "ModelCache")]
        public IActionResult ShowTable()
        {
            var additionalServices = db.TypesOfRecreations.ToList();
            return View(additionalServices);
        }
    }
}

lab4/Controllers/VoucherController.cs
using lab4.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace lab4.Controllers
{
    public class VoucherController : Controller
    {
        private TouristAgency1Context db;

        public VoucherController(TouristAgency1Context context)
        {
            db = context;
        }

        [ResponseCache(CacheProfileName = "ModelCache")]
        public IActionResult ShowTable()
        {
            var vouchers = db.Vouchers
                .Include(ia => ia.Client)
                .Include(ia => ia.TypeOfRecreation)
                .ToList();
            return View(vouchers);
        }
    }
}

lab4/Views/Client/ShowTable.cshtml
@{
    ViewData["Title"] = "Клиенты";
    @model List<Client>;

}

<div class="text-center">
    <table class="table">
        <tr>
            <th>Id</th>
            <th>ФИО</th>
            <th>Дата рождения</th>
            <th>Пол</th>
            <th>Адрес</th>
            <th>Серия паспорта</th>
            <th>Номер паспорта</th>
            <th>Скидка</th>
        </tr>
        @foreach (var clients in Model)
        {
            <tr>
                <td>
                    @clients.Id
                </td>
                <td>
                    @clients.Fio
                </td>
                <td>
                    @clients.DateOfBirth
                </td>
                <td>
                    @clients.Sex
                </td>
                <td>
                    @clients.Address
                </td>
                <td>
                    @clients.Series
                </td>
                <td>
                    @clients.Number
                </td>
                <td>
                    @clients.Discount
                </td>
            </tr>
        }
    </table>
</div>

lab4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Туристическое агенство</h1>
</div>

lab4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lab4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="ShowTable">Клиенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TypesOfRecration" asp-action="ShowTable">Виды отдыха</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voucher" asp-action="ShowTable">Путёвки</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - lab4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

lab4/Views/TypesOfRecration/ShowTable.cshtml
@{
    ViewData["Title"] = "Виды отдыха";
    @model List<TypesOfRecreation>;

}

<div class="text-center">
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>Описание</th>
            <th>Ограничения</th>
        </tr>
        @foreach (var typesOfRecration in Model)
        {
            <tr>
                <td>
                    @typesOfRecration.Id
                </td>
                <td>
                    @typesOfRecration.Name
                </td>
                <td>
                    @typesOfRecration.Description
                </td>
                <td>
                    @typesOfRecration.Restrictions
                </td>
            </tr>
        }
    </table>
</div>

lab4/Views/Voucher/ShowTable.cshtml
@{
    ViewData["Title"] = "Путёвка";
    @model List<Voucher>;

}

<div class="text-center">
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Дата начала</th>
            <th>Дата окончания</th>
            <th>Услуга</th>
            <th>Клиент</th>
            <th>Бронирование</th>
            <th>Оплата</th>
        </tr>
        @foreach (var voucher in Model)
        {
            <tr>
                <td>
                    @voucher.Id
                </td>
                <td>
                    @voucher.StartDate
                </td>
                <td>
                    @voucher.ExpirationDate
                </td>
                <td>
                    @voucher.TypeOfRecreation.Name
                </td>
                <td>
                    @voucher.Client.Fio
                </td>
                <td>
                    @voucher.Reservation
                </td>
                <td>
                    @voucher.Payment
                </td>
            </tr>
        }
    </table>
</div>